### ISSUE TITLE
Question: Tween + scrollY + fire off an event / call a function

### ISSUE THREAD

**Issue by matt-d-rat** [gilbox/react-imation#1]
Hey, great library, just a quick question, what's the best way to fire an event when using tween and scrollY?

My use case is, given I have the following reference in my React component to an HTML5 video child node:

```
<video ref={(c) => this._video = c}></video>
```

What would be the best way of pausing a HTML5 video when the tween using scrollY and posTopTop is greater than a certain scroll value, and playing the video when it is less than that value? Would you be able to provide an example that shows firing off an event or calling a function in this manner?

**Comment by gilbox** [comment]
It's been a while since I played with video, so this might not make sense, but how do you normally play/pause a video? If you can create a Video component with a `playing` prop it would be simply something like this:

```
<Video 
  playing={posTopTop > 400 && posTopTop < 800} 
  ref={c => this._video =c} />
```

**Comment by matt-d-rat** [comment]
@gilbox  You would interact with the `<video>` tag through the [HTMLMediaElement API](https://developer.mozilla.org/en/docs/Web/API/HTMLMediaElement), typically calling the `pause()`, `stop()` or `play()` methods on the DOM node:

```
var v = document.getElementsByTagName("video")[0];
v.pause();
```

So I'm unsure how to do this in React land with the react-track / react-imation library.

**Comment by gilbox** [comment]
In that case the `<Video />` component:

```
<Video 
  playing={posTopTop > 400 && posTopTop < 800} />
```

 could look something like this:

```
class Video extends React.Component {
   componentDidMount() {
      if (this.props.playing) this._video.play();
      else this._video.pause();
  }
   componentWillReceiveProps(nextProps) {
    if (nextProps.playing !== this.props.playing) { // maybe this if check is unecessary
      if (nextProps.playing) this._video.play();
      else this._video.pause();
    }
  }
  render() {
    return <video {...this.props} ref={(c) => this._video = c} />
  }
}
```

**Comment by matt-d-rat** [comment]
Ah I see, yep that did the trick. I had to make a minor adjustment to your suggestion:

```
class Video extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    togglePlaying() {
        if (this.props.playing) {
            React.findDOMNode(this._video).play();
        }
        else {
            React.findDOMNode(this._video).pause();
        }
    }

    componentDidMount() {
        this.togglePlaying();
    }

    componentDidUpdate() {
        this.togglePlaying();
    }

    shouldComponentUpdate(nextProps) {
        return nextProps.playing !== this.props.playing;
    }

    render() {
        return (
            <video {...this.props} ref={(c) => this._video = c}>
                {this.props.children}
            </video>
        );
    }
}

export default Video;
```

```
<Video playing={scrollY < 800} autoPlay loop muted preload>
    <source src="assets/video/big_buck_bunny.mp4" type="video/mp4"></source>
    <source src="assets/video/big_buck_bunny.ogv" type="video/ogg"></source>
    <source src="assets/video/big_buck_bunny.webm" type="video/webm"></source>
</Video>
```

Thanks for your help and for the awesome library. Keep up the good work!
