### ISSUE TITLE
instructions on how to build the examples

### ISSUE THREAD

**Issue by asfktz** [gilbox/react-imation#3]
Hi,

LOVE what you doing here

I tried to run the examples locally with no success:

`npm install` 
`cd examples`
`webpack`

what I get is this file structure:
react-imation/**examples/examples/**build****

![screen shot 2015-10-05 at 3 02 46 pm](https://cloud.githubusercontent.com/assets/199747/10279922/2d9c0c88-6b72-11e5-84a9-85fe31c3bcc0.png)

![screen shot 2015-10-05 at 3 10 31 pm](https://cloud.githubusercontent.com/assets/199747/10280089/484cff3c-6b73-11e5-923b-a01cd9fd368f.png)

**Comment by gilbox** [comment]
Sorry about that. No need to cd into `examples`...

```
npm i
npm run examples
```

**Comment by asfktz** [comment]
Thanks (:
