### ISSUE TITLE
timeline not stops after end, happens only with timeliner prop

### ISSUE THREAD

**Issue by asfktz** [gilbox/react-imation#6]
![oct 05 2015 21 08](https://cloud.githubusercontent.com/assets/199747/10289077/3b7e90c2-6ba5-11e5-91a7-3125badfda7c.gif)

bug demo:
https://www.dropbox.com/s/df74z07myrx35cq/bugdemo.zip?dl=0
`npm i`
`npm start`

**Comment by gilbox** [comment]
Thanks for this I'll definitely look into it.

**Comment by asfktz** [comment]
No problem (:

**Comment by gilbox** [comment]
So it turns out this is expected behavior. 

``` jsx
          <Timeline min={ 0 } max={ 100 }  >
            {timeliner => (<Content timeliner={ timeliner } />)}
          </Timeline>
```

is equivalent to:

``` jsx
          <Timeline timeliner={ new Timeliner({min: 0, max: 100}) } >
            {timeliner => (<Content timeliner={ timeliner } />)}
          </Timeline>
```

If you change your code it should work.

Btw, for anyone else reading this, I would never instantiate `Timeliner` class inside of `timeliner` prop but this is just for testing purposes.

**Comment by asfktz** [comment]
That does make a lot of sense..!
