### ISSUE TITLE
Not correct version on NPM

### ISSUE THREAD

**Issue by alec-chernicki** [gilbox/react-imation#8]
Unfortunately I can't seem to access the neonate function within the package. When inspecting the `react-imation` folder that's downloaded directly through NPM the neonate.js file isn't even included. It seems like the public NPM version might be a few version behind what's on GitHub?

**Comment by gilbox** [comment]
@alecortega I don't understand, what is `neonate.js` ?

**Comment by alec-chernicki** [comment]
@gilbox 
Sorry I think I've tracked it down. When installing `react-imation` at version 0.5.3. The files contained within the package are as follows: 
<img width="244" alt="screen shot 2016-08-02 at 7 32 51 pm" src="https://cloud.githubusercontent.com/assets/6596787/17348914/edcf29dc-58e7-11e6-926a-556d3415fda9.png">

In the src you have up on GitHub there is an index file which is the main entry point that exports the function neonate that we can require like 

``` js
import { neonate } from 'react-imation'
```

The problem is that this function does not exist in the index.js file that is on the public npm repository. So when I go to require it like above I get the following error. 

<img width="457" alt="screen shot 2016-08-02 at 7 37 34 pm" src="https://cloud.githubusercontent.com/assets/6596787/17349006/96e2ef68-58e8-11e6-98fb-37e6541baac1.png">

There also seems to be a mismatch where in your examples you refer to pulling in `'react-imation/neonate-value-factories'` but it's named 'react-imation/neonate-value-factories' in the public NPM version.

**Comment by gilbox** [comment]
[neonate does not show up anywhere in this codebase](https://github.com/gilbox/react-imation/search?utf8=%E2%9C%93&q=neonate)... can you link to or post the exact code where you think this comes up?
